name = "Mike Wood";
email = "Mikewwood@icloud.com";
street_address = "Gainsborough Lane";
age = 37;
house_number = 2;
deposit_amount = 1200.00;
bank_amount = 1000000.00;
deposit_paid = true;
bank_amount_valid = false;
puts "";
puts "Hello #{name}. You are #{age} years old.";
puts "You live at #{house_number} #{street_address}.";
puts "You stated your bank account currently has a very impressive value of #{bank_amount}!";
bank_amount -= deposit_amount;
puts "You have indicated you paid your deposit.";
puts "Our records indicate that that statement is #{deposit_paid}";
puts "Your new bank account balance is therefore #{bank_amount}";
puts "Our AI software has determined that your originally reported bank account balance is #{bank_amount_valid}.";
name = "Mike The Liar";
bank_amount = 1200.00;
puts "After recalculating, your actual starting bank account balance is in fact: #{bank_amount}";
bank_amount -= deposit_amount;
puts "After the deposit of #{deposit_amount} your new balance is therefore #{bank_amount}.";
insincere_statement = "Feel better and keep your chin up!";
puts "You have been renanmed #{name}.";
puts "Please receive the following sincere statement: #{insincere_statement}";
puts "";